### ISSUE TITLE
Remove jq dependency

### ISSUE THREAD

**Issue by pontikos** [phenopolis/phenogenon#1]
https://github.com/phenopolis/phenogenon/blob/8abf0d5c4ac9cf7e1b1b3a6e76b2689d33cd29bb/lib/phenogenon.py#L58

You don't need jq, you can do everything in python.

**Comment by IsmailM** [comment]
Actually, I feel that JQ is an easy to install dependency (i.e. you simply have to wget a link, producing a single precompiled jq file)...

I think we should simply have the way that JQ is run (i.e. change from full path to just `jq`)...

We will of course have to document this if we go down this path

**Comment by pontikos** [comment]
Also if you use Docker this is not so much an issue so I agree this is low priority for now.

**Comment by logust79** [comment]
done in commit https://github.com/phenopolis/phenogenon/commit/3bbbf132a29671b2372c2b4f371f87994cce7a6a
