### ISSUE TITLE
remove everything unecessary

### ISSUE THREAD

**Issue by pontikos** [phenopolis/phenogenon#2]
Lots of code is not used.

For instance there should be no code relating to phenopolis or to the mongodb.

phenogenon needs to be a standalone tool.

**Comment by pontikos** [comment]
Yes all these absolute paths need to be made into relative paths.

**Comment by logust79** [comment]
done in commit https://github.com/phenopolis/phenogenon/commit/3bbbf132a29671b2372c2b4f371f87994cce7a6a
