### ISSUE TITLE
Unit Testing requires a 60GB Gnomad VCF file

### ISSUE THREAD

**Issue by IsmailM** [phenopolis/phenogenon#5]
Currently it is looking for the following file: `tests/data/gnomad_data/vcf/exomes/gnomad.exomes.r2.0.1.sites.vcf.gz`

Accordng to [http://gnomad.broadinstitute.org/downloads](http://gnomad.broadinstitute.org/downloads), this file is around 60GB (which would be difficult to download on Travis - So need to think of alternative? - maybe just one chr?

**Comment by pontikos** [comment]
Agreed.  Chrom 22 ?

What's the information you can need from that file?

**Comment by IsmailM** [comment]
The two exemplar genes are:

- ABCA4 - which is on chr 1
- SCN1A - which is on chr 2

**Comment by pontikos** [comment]
I think tabix supports direct http/https access?

**Comment by logust79** [comment]
In the original folder, there is a complete gnomad file set in `tests/data`, which would make the tests pass and not taking a lot of space.
